<?php

namespace Stillat\Meerkat;

use Stillat\Meerkat\Http\RequestHelpers;
use Stillat\Meerkat\Providers\AddonServiceProvider;
use Stillat\Meerkat\Providers\NavigationServiceProvider;
use Stillat\Meerkat\ControlPanel\AddonNavIcons;
use Stillat\Meerkat\ControlPanel\Navigation;

class ServiceProvider extends AddonServiceProvider
{
    protected $routes = [
        'cp' => __DIR__.'/../routes/cp.php'
    ];

    protected $providers = [
        NavigationServiceProvider::class
    ];

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }


}
